// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9b5o-LZO7sEBMjkR-_dQwYYwWrc2o7nU',
    appId: '1:21827242928:web:a71ece5f589d012f662475',
    messagingSenderId: '21827242928',
    projectId: 'braille-70ade',
    authDomain: 'braille-70ade.firebaseapp.com',
    databaseURL: 'https://braille-70ade-default-rtdb.firebaseio.com',
    storageBucket: 'braille-70ade.appspot.com',
    measurementId: 'G-WFE3PHL5FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzZTH2Bi7sBn6LVWz_g2lVPruO2Fg1s7s',
    appId: '1:21827242928:android:3d4a5cb78fca1257662475',
    messagingSenderId: '21827242928',
    projectId: 'braille-70ade',
    databaseURL: 'https://braille-70ade-default-rtdb.firebaseio.com',
    storageBucket: 'braille-70ade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwt5FAb-MOdYnWx3etaRq0Zp7tXXhFoc',
    appId: '1:21827242928:ios:f5f9b7c1c3db0861662475',
    messagingSenderId: '21827242928',
    projectId: 'braille-70ade',
    databaseURL: 'https://braille-70ade-default-rtdb.firebaseio.com',
    storageBucket: 'braille-70ade.appspot.com',
    iosBundleId: 'com.example.brailleSih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwt5FAb-MOdYnWx3etaRq0Zp7tXXhFoc',
    appId: '1:21827242928:ios:ef924cdc63b78460662475',
    messagingSenderId: '21827242928',
    projectId: 'braille-70ade',
    databaseURL: 'https://braille-70ade-default-rtdb.firebaseio.com',
    storageBucket: 'braille-70ade.appspot.com',
    iosBundleId: 'com.example.brailleSih.RunnerTests',
  );
}
